### ISSUE TITLE
Text and Link Cleanup in Develop and Master Branches

### ISSUE THREAD

**Issue by grettygoose** [FredHutch/Oncoscape#107]
Oncoscape Develop and Master homepage branch differences
1.) (Oncoscape/) In Master but not Develop
          a. CONTRUBUTING
          b.  Cheatsheet

2.) (Oncoscape/) In Develop but not Master
          a. README.txt
          b. RemoveInstalledOncoscapePackages.R

Broken Links in Master Branch:
          a. Oncoscape/cheatsheet.md -Branching Model link broken
          b. Oncoscape/README.md - Install instructions link broken and INSTALL.txt link
          c. Wiki page needs to be updated if we want to continue to use it
          d. Oncoscape/dataPackages/- README- Oncoscape/dataPackages links (2 references),          
             Oncoscape/dataPackages/TCGAgbm, TCGAgbmcreateEventList.R, TCGAgbm copy number,    
             TCGAgbm, All links under the Data Package heading

**Comment by LisaMc** [comment]
@grettygoose these issues should be fixed by PR #121 and #122 please let me know if I missed anything

**Comment by grettygoose** [comment]
This comment is out of date, closing it.
