### ISSUE TITLE
"busy cursor" or equivalent needed

### ISSUE THREAD

**Issue by pshannon-bioc** [FredHutch/Oncoscape#112]
I think we all agree on this, but other tasks and priorities have conspired against any progress.

By creating this issue, I hope we give it the attention I believe it needs.

The most vivid need arises during the data loading interval, which takes place once a dataset is selected.  

github itself has an elegant solution:  while data is being assembled, and before the next page's UI is ready, the whole page is grayed out, and a spinning icon is displayed.   I think we should do the same.  The user would be able to see the steady progress in tab readiness as things progress (kudos to Lisa for this feature!).

Perhaps Jenny's new skills with css could be applied here?

**Comment by LisaMc** [comment]
@pshannon-bioc 
there's the loading data message while the constructor executes, then the dataset specified message is broadcast to all listeners.  It's at that point the top tab gets greyed out. The hub.enableTab function is called when the final steps for initializing the tab are complete.  What do you think about having a standard function for each tab, similar to "datasetSpecified,"  to indicate the tab is ready for user interaction?  This function can be the bookend that ends the wait cursor feature proposed here.

**Comment by pshannon-bioc** [comment]
I like it!

**Comment by grettygoose** [comment]
Michael added this feature March 2016
