### ISSUE TITLE
browser warning when using oncoscape from iphone 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/Oncoscape#117]
When I connect to oncoscape on my iphone / ipad with chrome v47 it warns me that it works best with chrome >v45

**Comment by LisaMc** [comment]
thanks @dirkpetersen We've been developing Oncoscape using Chrome and haven't done the cross browser compatibility testing yet to know how it performs elsewhere; hence the alert.  Until we are able to do such testing and optimization, do you have other recommendations to handle this in the meantime?

**Comment by dirkpetersen** [comment]
@LisaMc, you are just checking for string chrome, If you want to be be precise in your error message I would write "Oncoscape is currently developed and tested under Chrome.  For best results, please use Chrome version 45.0 and later on Windows, Mac OSX or Linux." 

If you want to exclude Chrome on IOS from the warning you could check for Chrome|CriOS ... see https://developer.chrome.com/multidevice/user-agent

**Comment by jordemort** [comment]
Chrome for iOS (and Firefox for iOS, and any other web browser for iOS that would be available from the app store) is just a wrapper around Safari's webview, so it makes more sense to treat it as Safari rather than Chrome.
