### ISSUE TITLE
update UI for datasets page

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#126]
Upon choosing a dataset to load, a dashboard of informative visuals about the data should be displayed instead of the manifest table.  This dashboard should include:
1. Layouts of the different data types and the available data within including expandable details about the provenance, eg RNA expression can have Affy, Illumina, and Nimblegen array or RNAseq datasets, each with details about where the data was obtained (TCGA website, UCSC, cBio, inhouse, etc), how it was processed (quantile normalized, ...), and any specific experimental conditions (cell lines, tumor types, ...).  Other data types include Clinical, copy number variation, mutation, protein abundance, miRNA levels, methylation, metabolites, etc.
2. Representative images of major properties of the data.  This can be the distribution of expression levels, the number of genes with mutations, bar plots of histology types/gender, number of patients, etc
3. Venn Diagram of overlapping IDs - to allow for comparing different data sources of the same data (UCSC, cBio, etc) as well as between data types (eg RNA & protein).  

Given the above diagrams, the user should be able to select individual, specific datasets for loading (eg a specific RNAseq expression dataset) and also specify if the full datatable using all IDs should be used, or if a subset using the intersection of overlapping IDs (eg those in both RNAseq and methylation data) should be loaded.

**Comment by grettygoose** [comment]
Allow users to view all these different plots and datasets as they choose on a single page for visual comparisons. Viewing unsupervised clustering plots such as MDs, PCA, dendrograms and heatmaps all on the same screen would be useful. Also viewing different patient subsets side by side (A vs B) would be a helpful added feature.
