### ISSUE TITLE
Update Patient Table for user defined columns

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#128]
The patient table tab currently has a pre-defined set of columns that are displayed, with the ability to show/hide any of them.
The SttrDataPackage includes a function that can return the patient history table with any of the available columns.  A button/menu should be made to allow the user to select the desired columns and redraw the table.

This will require a javascript call using a websocket function to R in order to grab the available column names for the user selection, and then another function to retrieve the appropriate table.

**Comment by alias-mac** [comment]
@canaantt no longer needed?

**Comment by canaantt** [comment]
@alias-mac Thank you for your attention:) 
Please checkout the dev site (https://dev.oncoscape.sttrcancer.io/). This feature has been implemented:) Please let us know if you have further questions.
