### ISSUE TITLE
alignment of patient timelines dropdown menus

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#132]
the positioning of the order by, align by and features dropdown menus is managed by <spans> which spill over to additional lines and create awkward layouts.  The width of the menus should be fixed with the internal dropdown having an auto width to fit the text lengths.  The text and menus should all fit on one line for most screen sizes, with the align by and order by menus stacking to the right (features float left) on small screens.

**Comment by grettygoose** [comment]
covered in Node JS push
