### ISSUE TITLE
auto fit timelines height when fit to page not selected

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#137]
By default, the timelines tab scales the height for each patient row in the plot so everything fits to the window height (and causes overlap in patient data).  Removing the "fit to page" selection gives a standard height for each patient row and enables y-axis scrolling.  However, the parent div is not expanded and the timelines overlaps the footer logos.  The parent div should also expand to the new div length.

**Comment by grettygoose** [comment]
Covered in Node JS push
