### ISSUE TITLE
adjust hoverbar in timelines

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#139]
the hover bar showing the entire row of events for a given patient doesn't seem to align properly with the horizontal positioning of the side plot and timeline graphs, causing some overhang on the left.  The calculation for position and length of the hoverbar needs to be revisited.

![screen shot 2015-12-07 at 11 02 29 am](https://cloud.githubusercontent.com/assets/5760217/11636697/2da78234-9cd2-11e5-84e6-8a89e8b7418b.png)

**Comment by grettygoose** [comment]
Covered in Node JS push
