### ISSUE TITLE
labels of x axis time units moved to below timelines plot

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#141]
Currently the "Years" and "Days" labels for the units of time being displayed in the timelines plot is showing within the plot area.  This causes issues when points are drawn over this area and the label is obscured.  The label should be moved to below the axis with the tick marks adjusted to accomodate.

![image](https://cloud.githubusercontent.com/assets/5760217/11636894/49ed1584-9cd3-11e5-8681-be1ef0245638.png)

**Comment by grettygoose** [comment]
Covered in Node JS push
