### ISSUE TITLE
TCGAluad and TCGAlusc need update on histology field name 

### ISSUE THREAD

**Issue by canaantt** [FredHutch/Oncoscape#165]
@LisaMc 
Thanks to @grettygoose 
In both diseases, the raw patient tables have duplicated names. The 2nd column explanation field (2nd row) is consistent with our other histology field (histological_type). I will create new feature branch and update TCGAluad, TCGAlusc and TCGAlung.

**Comment by grettygoose** [comment]
Thanks @canaantt 
We should double check all the red fields in my document to make sure that is the correct naming scheme for each disease type. :+1:
