### ISSUE TITLE
notify disease working group when the new feature is deploy

### ISSUE THREAD

**Issue by canaantt** [FredHutch/Oncoscape#176]
@LisaMc @robert-mcdermott @pshannon-bioc 
I'm adding this to see if we could send notify disease-working group such as Dr. Holland lab to play with the beta version. This could also contribute to the stability testing. Maybe after one feature-branch merged into either master branch or develop branch, this could trigger an email. Open to discussion.

**Comment by grettygoose** [comment]
This feature is enabled and directions will go out in the newsletter. We will push the updates through user emails.
