### ISSUE TITLE
Search Box issues not limited to Markers&Patients 

### ISSUE THREAD

**Issue by canaantt** [FredHutch/Oncoscape#180]
@LisaMc @pshannon-bioc @canaantt
Just want to confirm here that search result actually build upon the previous display but not clear the whole canvas.

- [ ] Search box needs instructions: search only takes one token at a time at this moment.
- [ ] Search box return search results. 
- [ ] Search box should allow fuzzy search by giving suggestions on gene name spelling
- [ ] use a different way to highlight the found nodes, such as beacon
- [ ] CNV+/- could be more specific as a GISTIC SCORE +2/-2, maybe using a tooltip to display this piece of information?

**Comment by grettygoose** [comment]
covered in Node JS push
