### ISSUE TITLE
Use various shapes to select

### ISSUE THREAD

**Issue by canaantt** [FredHutch/Oncoscape#19]
except for rectangle, maybe circle too?

**Comment by pshannon-bioc** [comment]
as in genes are rectangles, tumors (patients) are circles?

**Comment by grettygoose** [comment]
@LisaMc @canaantt 

What tab? M&P? I'm sure this will be covered in the node push but I want to make sure before closing it

**Comment by grettygoose** [comment]
Covered in Node JS push
