### ISSUE TITLE
Timelines error on Node branch

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#199]
![image](https://cloud.githubusercontent.com/assets/5760217/12684593/9e2bf762-c674-11e5-8f7c-74f6c2e3f0e0.png)

**Comment by mzager** [comment]
This error is the result of the variables defined in m4-workarounds.txt, not being included in the new build.  A fix will be in today.

**Comment by LisaMc** [comment]
angular rework solved issue
