### ISSUE TITLE
Relabel axis ticks by sensical values in Timelines

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#202]
Currently the x-axis shows number of days once the events are aligned by a certain event date.  This makes the number of days to be quite large and not meaningful.  Reconfigure to something like "3 days", "6 months", "1 year", "10 years"

![screen shot 2016-02-08 at 3 40 20 pm](https://cloud.githubusercontent.com/assets/5760217/12903141/48eadddc-ce7a-11e5-84d2-50ce851c0546.png)

**Comment by grettygoose** [comment]
covered in Node JS push

**Comment by grettygoose** [comment]
![screen shot 2016-03-29 at 5 20 20 pm](https://cloud.githubusercontent.com/assets/15098135/14128107/996dec48-f5d2-11e5-8ce2-1730f9a52cb2.png)
