### ISSUE TITLE
color pca plot by classifications

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#205]
include a drop down menu that allows patients to be colored according to some classification, as done in Markers & Patients.

**Comment by paul-shannon** [comment]
Hi Lisa,

You'll find this feature is already implemented, using the new Groups package, in the branch for which I issued a PR a few weeks ago: pshannon-refactor-server-2.   See Oncoscape/webapplets/pca/ and the screenshot below.

 - Paul

![image](https://cloud.githubusercontent.com/assets/2480712/12925463/47218b06-cf13-11e5-9c4b-6a5842fc95bd.png)
