### ISSUE TITLE
TCGA datapackage update

### ISSUE THREAD

**Issue by canaantt** [FredHutch/Oncoscape#21]
Prostate, Breast, Lung and Colorectal

**Comment by LisaMc** [comment]
breast has been updated.  @canaantt please model the others accordingly
Each package should have
[ ] getPatientIDs() in class
[ ] catList data structure created by createEventTypeList 
[ ] ptList data structure created by  createPatientList
[ ] eventTypeList created by createEventTypeList 
[ ] tbl.ptHistory data.frame created by createPatientTable
[ ] use getEventList in tests

**Comment by canaantt** [comment]
![screen shot 2015-10-28 at 6 55 30 pm](https://cloud.githubusercontent.com/assets/1596638/10808182/a614edc0-7da5-11e5-9be6-28ecaf8303b7.png)

**Comment by canaantt** [comment]
https://brucebcampbell.wordpress.com/2014/04/22/cleaning-up-git-repository-after-failed-push-with-large-file/

**Comment by pshannon-bioc** [comment]
pulled dataSet branch into develop.
to verify:
   cd ~/tmp; mkdir test; cd test
   git clone -b develop --single-branch https://github.com/FredHutch/Oncoscape
   make test
