### ISSUE TITLE
Fix help wanted link in wiki

### ISSUE THREAD

**Issue by pquentin** [FredHutch/Oncoscape#243]
It got [fixed in CONTRIBUTING.md](https://github.com/FredHutch/Oncoscape/commit/d96276931c45b121a49642a0f713d509a0376233) but it's still present in https://github.com/FredHutch/Oncoscape/wiki/Contribution: the dash got replaced by a space.

(Why the duplication, anyway?)

**Comment by GalaticStryder** [comment]
https://github.com/FredHutch/Oncoscape/wiki/Contribution/_history
Your change hasn't been pushed yet to the Wiki, this is what changed on the latest: https://github.com/FredHutch/Oncoscape/wiki/Contribution/_compare/b42bbaae4a93fb17c578d4851a96cf5448dff011
Your change might have been merged after this one.

**Comment by canaantt** [comment]
@GalaticStryder @pquentin 
We fixed this issue. Thank you for your comments!
