### ISSUE TITLE
help-wanted link in Contribution wiki page is broken

### ISSUE THREAD

**Issue by SeanKilleen** [FredHutch/Oncoscape#244]
(Would submit a PR for this but I'm not sure there's a way to do so for wiki pages).

Hi all,

On [the contribution page in the wiki](https://github.com/FredHutch/Oncoscape/wiki/Contribution), in the "What needs to be done?" section, the following link is used to link to the help wanted label:

> https://github.com/FredHutch/Oncoscape/labels/help-wanted

However, this results in an empty issues list: 

![image](https://cloud.githubusercontent.com/assets/2148318/14366073/015695ea-fcdf-11e5-8b18-f767e7c7c5fc.png)

I believe the correct link is: 
 
> https://github.com/FredHutch/Oncoscape/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

This is a great project idea, and I wanted to submit this so that others see there are definitely help-wanted issues out there!

**Comment by canaantt** [comment]
@SeanKilleen Thank you! I think I fixed it. Let me know if you have other questions!

**Comment by SeanKilleen** [comment]
@canaantt Yep! Looks good to me now. :) Will do, thanks!
