### ISSUE TITLE
TEST (Server, Branch & Pipeline)

### ISSUE THREAD

**Issue by grettygoose** [FredHutch/Oncoscape#261]

**Comment by robert-mcdermott** [comment]
The new long running CICD branch "test" has been created. Commits and merges to the "test" branch will now flow out to https://oncoscape-test.fhcrc.org/.  Make sure that anything merged to "test" has the a circle.yml file in the root of the repo that matches the current (just updated) "develop" branch version with the "test" branch pipeline defined in the deployment section.

**Comment by robert-mcdermott** [comment]
The merge of PR #280 closed this issue
