### ISSUE TITLE
app-wide testing

### ISSUE THREAD

**Issue by pshannon-bioc** [FredHutch/Oncoscape#30]
Our goal is to have comprehensive QUnit tests within every tab.
app-wide testing runs all of these in sequence, and adds some demanding simulated workflows, from tab to tab also.

Immediate goal:
   1. complete Markers & Patients intra-tab testing
   2. add another tab
   3. use these as constituents of a preliminary app-wide testing for oncotest1

**Comment by LisaMc** [comment]
@pshannon-bioc can you send the command line call for the M&P and datasets tabs to @robert-mcdermott so he can include them in the master tests?

**Comment by pshannon-bioc** [comment]
deferred for now, for two reasons, and with one note of reassurance:
  1) coordinating successive tab testing, in testManager/Module.js, needs work.
     needs to dependably track progress through a "higher level" hidden status div
 2) we need to evaluate Ben's suggestion that tabs are loaded only when needed
    (this would affect the testing strategy; now all tabs are loaded as if de novo
     whenever a dataset is selected, which happens MANY times in the course of testing)
3) a semblance of cross-tab comprehensive testing can be had through running "make test"
   in each tab.   we have 2 such tests now.  our focus is on creating more
