### ISSUE TITLE
from PCA to survival

### ISSUE THREAD

**Issue by canaantt** [FredHutch/Oncoscape#34]
The PCA sends sample barcode rather than patient id to survival.

![screen shot 2015-10-15 at 12 16 02 pm](https://cloud.githubusercontent.com/assets/1596638/10524842/8428e3f2-7336-11e5-9b96-2a1627b995ca.png)
![screen shot 2015-10-15 at 12 16 25 pm](https://cloud.githubusercontent.com/assets/1596638/10524857/91a5cc0c-7336-11e5-92a6-68554f76bfaf.png)

**Comment by LisaMc** [comment]
Fixed by passing IDs through a getPatientID() command in the survival R code that is data package specific --- still needs testing
