### ISSUE TITLE
Warning messages in running test_TCGAlgg.R

### ISSUE THREAD

**Issue by klatoza** [FredHutch/Oncoscape#37]
1: In SttrDataPackage:::.loadFiles(dir) : no networks found
2: In SttrDataPackage:::.loadFiles(dir) : no categorized samples found
3: In SttrDataPackage:::.loadFiles(dir) : no networks found
4: In SttrDataPackage:::.loadFiles(dir) : no categorized samples found
5: In SttrDataPackage:::.loadFiles(dir) : no networks found
6: In SttrDataPackage:::.loadFiles(dir) : no categorized samples found
7: In SttrDataPackage:::.loadFiles(dir) : no networks found
8: In SttrDataPackage:::.loadFiles(dir) : no categorized samples found
9: In SttrDataPackage:::.loadFiles(dir) : no networks found
10: In SttrDataPackage:::.loadFiles(dir) : no categorized samples found
>

**Comment by LisaMc** [comment]
similar to #57 .  Is there a way to make default networks @pshannon-bioc ?

**Comment by grettygoose** [comment]
@LisaMc is this still relevant?
