### ISSUE TITLE
Python modules need to be installed before running tests described in make files

### ISSUE THREAD

**Issue by klatoza** [FredHutch/Oncoscape#39]
python testPCAWebSocketOperations.py
Traceback (most recent call last):
  File "testPCAWebSocketOperations.py", line 2, in <module>
    from websocket import create_connection
ImportError: No module named websocket

**Comment by klatoza** [comment]
Need to install Microsoft Visual C++ Compiler for Python 2.7 see 
http://www.microsoft.com/en-us/download/confirmation.aspx?id=44266
to install modules like websocket

**Comment by klatoza** [comment]
https://pypi.python.org/pypi/websocket-client is the socket package used

**Comment by LisaMc** [comment]
@robert-mcdermott can you please verify these dependencies are described and linked to in the documentation?

**Comment by robert-mcdermott** [comment]
@klatoza @LisaMc  this is not an issue as the websocket-client client module can be installed on a Windows system easily via pip:

```bash
C:\Users\su_rmcdermo>pip install websocket-client
Collecting websocket-client
  Downloading websocket_client-0.34.0.tar.gz (193kB)
    100% |################################| 196kB 307kB/s
Collecting six (from websocket-client)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, websocket-client
  Running setup.py install for websocket-client
Successfully installed six-1.10.0 websocket-client-0.34.0
```

After installing it imports without error:

```bash
C:\Users\su_rmcdermo>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import websocket
```

Pip is included in the default install of Python starting from versions 2.7.9 and 3.4.0 and can be installed in older versions of Python easily with the pip bootstrap script found here: https://bootstrap.pypa.io/get-pip.py

The install documentation I'm working on will include information on installing the websocket-client module via pip.

With this information I'm closing #39 as we don't need to install the Microsoft Visual C++ Compiler to get this module installed as previously thought. By using pip, the websocket-client module is installed exactly the same on Windows as it is on Linux.
