### ISSUE TITLE
After stopping PLSR test on windows test gets a warning message

### ISSUE THREAD

**Issue by klatoza** [FredHutch/Oncoscape#40]
The following message is delivered after the test is ended on Windows

Warning message:
In summarizeNumericPatientAttributes(myplsr, attributes) :
  unrecognized patient history attribute: 'bogus'

Was this planned in the test?

**Comment by LisaMc** [comment]
@pshannon-bioc this is in analysisPackages/PLSR/unitTests.  Is this intentional or does it require cleanup?

**Comment by LisaMc** [comment]
warning message was on purpose to ensure bogus tests being reported
