### ISSUE TITLE
Qunit test PCA

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#60]
- [x]   Calculate updates plot
- [ ]   tooltip shows patient name
- [x]   geneset menu populated
- [ ]   clear selection removes highlight
- [ ]  use all samples in dataset generates default plot

**Comment by canaantt** [comment]
@LisaMc @pshannon-bioc 
The makefile requires runPca.R, which is missing at least from develop branch.  Please advise.
