### ISSUE TITLE
Provide more descriptive dataset name in “Available Datasets”

### ISSUE THREAD

**Issue by robert-mcdermott** [FredHutch/Oncoscape#71]
The datasets in the "Available Datasets" selection drop-down has very nondescript names; add more descriptive names. Mockup example below:

>![image](https://cloud.githubusercontent.com/assets/7399563/10833769/b4f7925a-7e51-11e5-9e5c-7a6548ab826f.png)

**Comment by grettygoose** [comment]
Michael- March 2016
