### ISSUE TITLE
Provide a global indicator of the currently loaded dataset 

### ISSUE THREAD

**Issue by robert-mcdermott** [FredHutch/Oncoscape#72]
After you switch to any tab other than the datasets tab, it's no longer clear which dataset is loaded. Make the loaded dataset globally visible. See mock up below:

>![image](https://cloud.githubusercontent.com/assets/7399563/10834150/3a30e4ce-7e54-11e5-870c-86e02eec4da2.png)

**Comment by grettygoose** [comment]
Michael fixed March 2016
