### ISSUE TITLE
oncoscape branch testing after update

### ISSUE THREAD

**Issue by canaantt** [FredHutch/Oncoscape#91]
@LisaMc 
This is what I did, correct me if I'm wrong.
mkdir newdir
cd newdir
git init
git clone
git checkout develop

cd Oncoscapefile:///Users/zhangj4/Library/R/3.2/
export PATH = /usr/bin/R
export R_LIB = /Users/zhangj4/Library/R/3.2 
make installLocal
![screen shot 2015-11-05 at 5 36 38 pm](https://cloud.githubusercontent.com/assets/1596638/10987258/93fe9018-83e6-11e5-863f-fb9a4f5f5db6.png)

**Comment by LisaMc** [comment]
@canaantt this is now covered in the INSTALL.md and cheetsheat files

**Comment by canaantt** [comment]
@LisaMc  Thanks!!! I forgot to close this earlier:) :thumbsup:
