### ISSUE TITLE
missing dependency "R.utils" in develop branch? 

### ISSUE THREAD

**Issue by robert-mcdermott** [FredHutch/Oncoscape#92]
I tried building, testing and running the develop branch on a clean system this morning. The build seems run successfully but "make test" fails for me with the following error:

```bash
> library(R.utils)
Error in library(R.utils) : there is no package called ‘R.utils’
Execution halted
make[1]: *** [test] Error 1
make: *** [test] Error 2
```
Is there a missing dependency (R.utils) that we need to add the install scripts?

I don't have this problem on the master branch. A 'make test' of master on a clean system is successful and completes with "OK:  all python websocket json tests passed"

If I install RUnit manually and run the test again if moves on to the following error:

```bash
Error in testCanonicalizePatientIDs() : 
  could not find function "canonicalizePatientIDs"
Calls: runTests -> testCanonicalizePatientIDs
Execution halted
make[1]: *** [test] Error 1
make: *** [test] Error 2
```

I'm not sure if there is really a problem or if I'm doing something wrong.  I did a "make installLocal", is "make test" not using the $R_LIBS var and only looking for system-wide packages? "make test" vs "make testLocal" (just an example, there is no testLocal target) type of mismatch?

Again not sure if this is a real issue or just something I don't understand.

**Comment by robert-mcdermott** [comment]
@LisaMc

**Comment by LisaMc** [comment]
Hi Robert,
I think your comments help point out the need for the make clean target.  Running the installLocal uses the libraries within a defined R_LIBS directory, but it seems possible that if a library is not defined there, then R will search for the package in other locations.  This is probably why my test passed without the R.utils being explicitly defined in the installBioconductorPackages.R, as it is installed elsewhere on my computer.  I'm not sure why the canonicalizePatientIDs error occurred as the tests passed on my machine, but will look into that now.

Thanks.
~Lisa

**Comment by LisaMc** [comment]
@robert-mcdermott even after a clean install, I can't seem to find the testing error for canonicalizePatientIDs.  Do you know which dataset this fails on?

**Comment by robert-mcdermott** [comment]
@LisaMc I don't know. Is the dataset it's testing obvious in the output before the error occurs? I tried this on my Desktop iMac this morning, but I'll try it again in a clean container (Linux rather than Mac OS) when I get a chance and see if I still encounter this.

**Comment by LisaMc** [comment]
If you look within the code just above the test failure there should be a line where the data package is getting loaded, e.g. TCGAgbm() which will give me a better idea of where to look

**Comment by robert-mcdermott** [comment]
@LisaMc when I get back to my desk I'll see if it's still in my terminal history, if not I'll attempt to reproduce it

**Comment by robert-mcdermott** [comment]
@LisaMc 

It was still in my terminal history and looks like it failed in 'DEMOdz' (see output below).

I'm going to start doing all my building/testing in a fresh container each run to make sure the environment always 100% clean and consistent.

```R
> #----------------------------------------------------------------------------------------------------
> testCanonicalizePatientIDs <- function()
+ {
+    printf("--- testCanonicalizePatientIDs")
+    dp <- DEMOdz()
+    IDs <- names(getPatientList(dp))
+    ptIDs <- canonicalizePatientIDs(dp, IDs)
+    
+    checkTrue(all(grepl("^TCGA\\.\\w\\w\\.\\w\\w\\w\\w$", ptIDs)))
+ 
+ }
> #----------------------------------------------------------------------------------------------------
> if(!interactive())
+    runTests()
[1] === test_DEMOdz.R, runTests()
[1] --- testManifest
[1] --- testExpression
[1] --- testExpression
[1] --- testCopyNumber
[1] --- testMutation
[1] --- testHistoryList
[1] SttrDataPackage ctor, networks.found: 4
[1] --- testHistoryTable
[1] SttrDataPackage ctor, networks.found: 4
[1] --- testConstructor
[1] SttrDataPackage ctor, networks.found: 4
[1] --- testHistoryTable
[1] SttrDataPackage ctor, networks.found: 4
[1] --- testNetworks
[1] SttrDataPackage ctor, networks.found: 4
[1] --- testSampleCategories
[1] SttrDataPackage ctor, networks.found: 4
[1] --- testCanonicalizePatientIDs
[1] SttrDataPackage ctor, networks.found: 4
Error in testCanonicalizePatientIDs() : 
  could not find function "canonicalizePatientIDs"
Calls: runTests -> testCanonicalizePatientIDs
Execution halted
make[1]: *** [test] Error 1
make: *** [test] Error 2
```
