### ISSUE TITLE
docker installation/use documentation

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#94]
Link a new docker installation documentation markdown file within the main install file
Document:
- [x] additional system requirements beyond Oncoscape needs
- [x] how to install docker
- [x] how to run oncoscape in container
- [x] how to develop oncoscape inside a container

**Comment by robert-mcdermott** [comment]
@LisaMc I was planning on adding Docker instructions to the INSTALL.md, but I can add it to an external document and link to it from inside INSTALL.md. I've been doing most of my work inside a container so it's possible to use containers for development as well as deployment.

**Comment by robert-mcdermott** [comment]
PR #113 closes this issue.
