### ISSUE TITLE
dependency "jshint" missing in develop branch

### ISSUE THREAD

**Issue by robert-mcdermott** [FredHutch/Oncoscape#98]
@pshannon-bioc @LisaMc, 'make test' of the develop branch freshly pulled from the repo on both Linux and Mac OS is failing with the following error: 

```
jshint Module.js
make[2]: jshint: Command not found
make[2]: *** [check] Error 127
make[2]: Leaving directory `/Oncoscape/Oncoscape/inst/scripts/datasets'
make[1]: *** [check] Error 2
make[1]: Leaving directory `/Oncoscape/Oncoscape/inst/scripts'
make: *** [test] Error 2
```

I'm guessing the installation script needs to include jshint.

**Comment by pshannon-bioc** [comment]
Yep!   We have seen that before, and have skated around it.  
How much trouble is it to install jshint on your build machines?

 - Paul

**Comment by robert-mcdermott** [comment]
@pshannon-bioc @LisaMc I installed npm then used npm to install the jshint package, but when I attempt to run jshint it complains because 'node' is not installed.  Of course I can also install 'node' but the more technology stacks that Oncoscape depends on the more difficult it is to get up and running, especially if the goal is to get it running on Windows (outside of a container). 

For example the following stuff is required to be installed for the testing that's not actually required to install and run the application:

- python
- pip
- python websocket-client module
- npm
- jshint node module
- node

On a side note, I can't even get the much simpler master branch version the 'make test' running clean on Windows. It just uses too much Unix tool chain stuff and conventions that even having cygwin installed is not enough. Windows uses different path separators than Mac/Linux ('\' vs '/'), Window environment variables are %var% vs $var, the ps aux, kill stuff can't work even with cygwin, etc...  I think the best approach if the goal is to be cross platform might be to dump unix tool chain stuff (make, m4, shell scripts, etc...) and re-write the install, test and run routines in Python.  I can get Oncoscape installed and running on Windows by adding some Windows specific make targets (figured it out, now ready to document and submit some makefile changes), the but getting the tests to run seems like it will be a major challenge.

**Comment by LisaMc** [comment]
@pshannon-bioc what do you think?  is python suitable and standard enough for installing and running Oncoscape across platforms?

**Comment by pshannon-bioc** [comment]
How about we give up on jshint except on developers’ own machines, skip node, npm, not plague Robert with so many prerequisites?

Python - yes.  Standard, portable, available everywhere.

Thanks, everybody!

 - Paul
